// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVy1hy_Ysa_sDdXgf6Ih8kvdnQHeO6pLA',
    appId: '1:447393041678:web:4cb56dcec59b9a91acdb5f',
    messagingSenderId: '447393041678',
    projectId: 'flashchat-bdb1c',
    authDomain: 'flashchat-bdb1c.firebaseapp.com',
    storageBucket: 'flashchat-bdb1c.appspot.com',
    measurementId: 'G-1LSTTN97YP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOPt_pNwp_nQlqOQSRfAfNnaTVW1lyV6c',
    appId: '1:447393041678:android:685ed1856c950152acdb5f',
    messagingSenderId: '447393041678',
    projectId: 'flashchat-bdb1c',
    storageBucket: 'flashchat-bdb1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTcNbDg3YX34yOYoYAfHJjHt-atpImn6I',
    appId: '1:447393041678:ios:e3cac65c74ee6b43acdb5f',
    messagingSenderId: '447393041678',
    projectId: 'flashchat-bdb1c',
    storageBucket: 'flashchat-bdb1c.appspot.com',
    iosClientId: '447393041678-d29vhscqnoj63nt55uqvck1si2ugnafh.apps.googleusercontent.com',
    iosBundleId: 'com.flashchat.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTcNbDg3YX34yOYoYAfHJjHt-atpImn6I',
    appId: '1:447393041678:ios:e3cac65c74ee6b43acdb5f',
    messagingSenderId: '447393041678',
    projectId: 'flashchat-bdb1c',
    storageBucket: 'flashchat-bdb1c.appspot.com',
    iosClientId: '447393041678-d29vhscqnoj63nt55uqvck1si2ugnafh.apps.googleusercontent.com',
    iosBundleId: 'com.flashchat.flashChat',
  );
}
